language: python
sudo: false
dist: trusty

python:
  - "2.7"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - pip install numpy matplotlib
  - python setup.py build_ext
  - python setup.py build_py
  - python setup.py install

# command to run tests
script:
  - python demo/CmfTutBoundary.py
